version: '3'

services:
  fdk-portal:
    image: eu.gcr.io/digdir-fdk-infra/fdk-portal:latest
    networks:
      fdk-network:
        aliases:
          - fdk-portal
    ports:
      - "8080:8080"
    environment:
      - SEARCH_API_HOST=https://www.fellesdatakatalog.digdir.no
      - SEARCH_FULLTEXT_HOST=https://search.fellesdatakatalog.digdir.no
      - CMS_API_HOST=https://cms-fellesdatakatalog.digdir.no
      - ORGANIZATION_HOST=https://organization-bff.fellesdatakatalog.digdir.no
      - ORGANIZATION_CATALOGUE_HOST=https://organization-catalogue.fellesdatakatalog.digdir.no
      - REPORT_API_HOST=https://reports-bff.fellesdatakatalog.digdir.no
      - METADATA_QUALITY_ASSESSMENT_API_HOST=https://metadata-quality.fellesdatakatalog.digdir.no
      - FDK_REGISTRATION_BASE_URI=https://registrering.fellesdatakatalog.digdir.no
      - ADMIN_GUI_BASE_URI=https://admin.fellesdatakatalog.digdir.no
      - INFORMATIONMODEL_HARVESTER_HOST=https://informationmodels.fellesdatakatalog.digdir.no
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    command: sh -c "pipenv run python3 src/selenium_driver.py"
    depends_on:
      - fdk-portal
    networks:
      - fdk-network
networks:
  fdk-network:
